///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace mhn_win_synctool_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The login recording.
    /// </summary>
    [TestModule("3bafe94b-55bf-4ec1-92c8-41a4887f16bb", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the mhn_win_synctool_testRepository repository.
        /// </summary>
        public static mhn_win_synctool_testRepository repo = mhn_win_synctool_testRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            var_username = "";
            var_password = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _var_username;

        /// <summary>
        /// Gets or sets the value of variable var_username.
        /// </summary>
        [TestVariable("a0f03df3-73b9-4d92-82ea-916f9af644af")]
        public string var_username
        {
            get { return _var_username; }
            set { _var_username = value; }
        }

        string _var_password;

        /// <summary>
        /// Gets or sets the value of variable var_password.
        /// </summary>
        [TestVariable("b9eb6b76-89eb-42b4-a1aa-a6c83f8e2ccd")]
        public string var_password
        {
            get { return _var_password; }
            set { _var_password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.0;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\Yuanhua Jiang\\AppData\\Local\\Apps\\2.0\\DDGVG1XC.K83\\HE6QNME7.5G9\\orga...app_6ffb2b575b86cf93_0001.0001_140fc0d6d81ff918\\Albelli.Frontend.MHNSync.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Users\\Yuanhua Jiang\\AppData\\Local\\Apps\\2.0\\DDGVG1XC.K83\\HE6QNME7.5G9\\orga...app_6ffb2b575b86cf93_0001.0001_140fc0d6d81ff918\\Albelli.Frontend.MHNSync.exe", "", "C:\\Users\\Yuanhua Jiang\\AppData\\Local\\Apps\\2.0\\DDGVG1XC.K83\\HE6QNME7.5G9\\orga...app_6ffb2b575b86cf93_0001.0001_140fc0d6d81ff918", false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrganisePhotosSyncTool.profile_tab' at 21;11.", repo.OrganisePhotosSyncTool.profile_tabInfo, new RecordItemIndex(1));
            repo.OrganisePhotosSyncTool.profile_tab.Click("21;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrganisePhotosSyncTool.UserLoginSettings.username_field' at 80;8.", repo.OrganisePhotosSyncTool.UserLoginSettings.username_fieldInfo, new RecordItemIndex(2));
            repo.OrganisePhotosSyncTool.UserLoginSettings.username_field.Click("80;8");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Back}'.", new RecordItemIndex(3));
            Keyboard.Press("{LControlKey down}{Akey}{LControlKey up}{Back}");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$var_username'.", new RecordItemIndex(4));
            Keyboard.Press(var_username);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrganisePhotosSyncTool.UserLoginSettings.password_field' at 70;13.", repo.OrganisePhotosSyncTool.UserLoginSettings.password_fieldInfo, new RecordItemIndex(5));
            repo.OrganisePhotosSyncTool.UserLoginSettings.password_field.Click("70;13");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$var_password'.", new RecordItemIndex(6));
            Keyboard.Press(var_password);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrganisePhotosSyncTool.UserLoginSettings.login_button' at 40;10.", repo.OrganisePhotosSyncTool.UserLoginSettings.login_buttonInfo, new RecordItemIndex(7));
            repo.OrganisePhotosSyncTool.UserLoginSettings.login_button.Click("40;10");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 50s for item 'OrganisePhotosSyncTool.UserLoginSettings.login_button' to not exist.", repo.OrganisePhotosSyncTool.UserLoginSettings.login_buttonInfo, new ActionTimeout(50000), new RecordItemIndex(8));
            repo.OrganisePhotosSyncTool.UserLoginSettings.login_buttonInfo.WaitForNotExists(50000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrganisePhotosSyncTool.UserLoginSettings.expand_loginForm_button' at 7;11.", repo.OrganisePhotosSyncTool.UserLoginSettings.expand_loginForm_buttonInfo, new RecordItemIndex(9));
            repo.OrganisePhotosSyncTool.UserLoginSettings.expand_loginForm_button.Click("7;11");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Logout') on item 'OrganisePhotosSyncTool.UserLoginSettings.logout_button'.", repo.OrganisePhotosSyncTool.UserLoginSettings.logout_buttonInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.OrganisePhotosSyncTool.UserLoginSettings.logout_buttonInfo, "Text", "Logout");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
