///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace mhn_win_synctool_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The logout recording.
    /// </summary>
    [TestModule("f8365668-f91e-4af0-9f5d-f829e7547682", ModuleType.Recording, 1)]
    public partial class Logout : ITestModule
    {
        /// <summary>
        /// Holds an instance of the mhn_win_synctool_testRepository repository.
        /// </summary>
        public static mhn_win_synctool_testRepository repo = mhn_win_synctool_testRepository.Instance;

        static Logout instance = new Logout();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Logout()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Logout Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.0;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\Yuanhua Jiang\\AppData\\Local\\Apps\\2.0\\DDGVG1XC.K83\\HE6QNME7.5G9\\orga...app_6ffb2b575b86cf93_0001.0001_140fc0d6d81ff918\\Albelli.Frontend.MHNSync.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Users\\Yuanhua Jiang\\AppData\\Local\\Apps\\2.0\\DDGVG1XC.K83\\HE6QNME7.5G9\\orga...app_6ffb2b575b86cf93_0001.0001_140fc0d6d81ff918\\Albelli.Frontend.MHNSync.exe", "", "C:\\Users\\Yuanhua Jiang\\AppData\\Local\\Apps\\2.0\\DDGVG1XC.K83\\HE6QNME7.5G9\\orga...app_6ffb2b575b86cf93_0001.0001_140fc0d6d81ff918", false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrganisePhotosSyncTool.profile_tab' at 20;8.", repo.OrganisePhotosSyncTool.profile_tabInfo, new RecordItemIndex(1));
            repo.OrganisePhotosSyncTool.profile_tab.Click("20;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrganisePhotosSyncTool.UserLoginSettings.expand_loginForm_button' at 7;2.", repo.OrganisePhotosSyncTool.UserLoginSettings.expand_loginForm_buttonInfo, new RecordItemIndex(2));
            repo.OrganisePhotosSyncTool.UserLoginSettings.expand_loginForm_button.Click("7;2");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrganisePhotosSyncTool.UserLoginSettings.logout_button' at 34;11.", repo.OrganisePhotosSyncTool.UserLoginSettings.logout_buttonInfo, new RecordItemIndex(3));
            repo.OrganisePhotosSyncTool.UserLoginSettings.logout_button.Click("34;11");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 50s for item 'OrganisePhotosSyncTool.UserLoginSettings.login_button' to exist.", repo.OrganisePhotosSyncTool.UserLoginSettings.login_buttonInfo, new ActionTimeout(50000), new RecordItemIndex(4));
            repo.OrganisePhotosSyncTool.UserLoginSettings.login_buttonInfo.WaitForExists(50000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'OrganisePhotosSyncTool.UserLoginSettings.login_button'.", repo.OrganisePhotosSyncTool.UserLoginSettings.login_buttonInfo, new RecordItemIndex(5));
            Validate.Exists(repo.OrganisePhotosSyncTool.UserLoginSettings.login_buttonInfo);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
