///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace mhn_win_synctool_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the mhn_win_synctool_testRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.1")]
    [RepositoryFolder("24365fec-fe6f-4847-b97b-ba176bb6a424")]
    public partial class mhn_win_synctool_testRepository : RepoGenBaseFolder
    {
        static mhn_win_synctool_testRepository instance = new mhn_win_synctool_testRepository();
        mhn_win_synctool_testRepositoryFolders.OrganisePhotosSyncToolAppFolder _organisephotossynctool;
        mhn_win_synctool_testRepositoryFolders.Win_taskBarAppFolder _win_taskbar;
        mhn_win_synctool_testRepositoryFolders.Win_systemTray_IconsAppFolder _win_systemtray_icons;
        mhn_win_synctool_testRepositoryFolders.Organise_photos_systemTray_optionsAppFolder _organise_photos_systemtray_options;

        /// <summary>
        /// Gets the singleton class instance representing the mhn_win_synctool_testRepository element repository.
        /// </summary>
        [RepositoryFolder("24365fec-fe6f-4847-b97b-ba176bb6a424")]
        public static mhn_win_synctool_testRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public mhn_win_synctool_testRepository() 
            : base("mhn_win_synctool_testRepository", "/", null, 0, false, "24365fec-fe6f-4847-b97b-ba176bb6a424", ".\\RepositoryImages\\mhn_win_synctool_testRepository24365fec.rximgres")
        {
            _organisephotossynctool = new mhn_win_synctool_testRepositoryFolders.OrganisePhotosSyncToolAppFolder(this);
            _win_taskbar = new mhn_win_synctool_testRepositoryFolders.Win_taskBarAppFolder(this);
            _win_systemtray_icons = new mhn_win_synctool_testRepositoryFolders.Win_systemTray_IconsAppFolder(this);
            _organise_photos_systemtray_options = new mhn_win_synctool_testRepositoryFolders.Organise_photos_systemTray_optionsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("24365fec-fe6f-4847-b97b-ba176bb6a424")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The OrganisePhotosSyncTool folder.
        /// </summary>
        [RepositoryFolder("32d98d55-9bc8-48d0-9474-628d8952b26b")]
        public virtual mhn_win_synctool_testRepositoryFolders.OrganisePhotosSyncToolAppFolder OrganisePhotosSyncTool
        {
            get { return _organisephotossynctool; }
        }

        /// <summary>
        /// The win_taskBar folder.
        /// </summary>
        [RepositoryFolder("613e494b-6889-434f-9255-1e70dc948e7b")]
        public virtual mhn_win_synctool_testRepositoryFolders.Win_taskBarAppFolder win_taskBar
        {
            get { return _win_taskbar; }
        }

        /// <summary>
        /// The win_systemTray_Icons folder.
        /// </summary>
        [RepositoryFolder("d4cdfe2f-d598-4cc9-87e2-0ea2262a0836")]
        public virtual mhn_win_synctool_testRepositoryFolders.Win_systemTray_IconsAppFolder win_systemTray_Icons
        {
            get { return _win_systemtray_icons; }
        }

        /// <summary>
        /// The organise_photos_systemTray_options folder.
        /// </summary>
        [RepositoryFolder("34c5abc1-46f6-4e61-9432-84b94ecf775e")]
        public virtual mhn_win_synctool_testRepositoryFolders.Organise_photos_systemTray_optionsAppFolder organise_photos_systemTray_options
        {
            get { return _organise_photos_systemtray_options; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.1")]
    public partial class mhn_win_synctool_testRepositoryFolders
    {
        /// <summary>
        /// The OrganisePhotosSyncToolAppFolder folder.
        /// </summary>
        [RepositoryFolder("32d98d55-9bc8-48d0-9474-628d8952b26b")]
        public partial class OrganisePhotosSyncToolAppFolder : RepoGenBaseFolder
        {
            mhn_win_synctool_testRepositoryFolders.UserLoginSettingsFolder _userloginsettings;
            RepoItemInfo _profile_tabInfo;

            /// <summary>
            /// Creates a new OrganisePhotosSyncTool  folder.
            /// </summary>
            public OrganisePhotosSyncToolAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OrganisePhotosSyncTool", "/form[@wpfnative='True' and @title='Organise.Photos Sync Tool' and @processname='Albelli.Frontend.MHNSync']", parentFolder, 30000, null, true, "32d98d55-9bc8-48d0-9474-628d8952b26b", "")
            {
                _userloginsettings = new mhn_win_synctool_testRepositoryFolders.UserLoginSettingsFolder(this);
                _profile_tabInfo = new RepoItemInfo(this, "profile_tab", ".//tabpagelist[@automationid='SyncTabControl']/tabpage[@automationid='ProfileTabItem']/text[@caption='Profile']", 30000, null, "5ec225b3-c4c8-449a-b29b-bd6b40494bbe");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("32d98d55-9bc8-48d0-9474-628d8952b26b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("32d98d55-9bc8-48d0-9474-628d8952b26b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The profile_tab item.
            /// </summary>
            [RepositoryItem("5ec225b3-c4c8-449a-b29b-bd6b40494bbe")]
            public virtual Ranorex.Text profile_tab
            {
                get
                {
                    return _profile_tabInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The profile_tab item info.
            /// </summary>
            [RepositoryItemInfo("5ec225b3-c4c8-449a-b29b-bd6b40494bbe")]
            public virtual RepoItemInfo profile_tabInfo
            {
                get
                {
                    return _profile_tabInfo;
                }
            }

            /// <summary>
            /// The UserLoginSettings folder.
            /// </summary>
            [RepositoryFolder("67c803e2-5f5f-4e0d-8d4e-8697d46a6e5c")]
            public virtual mhn_win_synctool_testRepositoryFolders.UserLoginSettingsFolder UserLoginSettings
            {
                get { return _userloginsettings; }
            }
        }

        /// <summary>
        /// The UserLoginSettingsFolder folder.
        /// </summary>
        [RepositoryFolder("67c803e2-5f5f-4e0d-8d4e-8697d46a6e5c")]
        public partial class UserLoginSettingsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _login_buttonInfo;
            RepoItemInfo _password_fieldInfo;
            RepoItemInfo _username_fieldInfo;
            RepoItemInfo _expand_loginform_buttonInfo;
            RepoItemInfo _logout_buttonInfo;

            /// <summary>
            /// Creates a new UserLoginSettings  folder.
            /// </summary>
            public UserLoginSettingsFolder(RepoGenBaseFolder parentFolder) :
                    base("UserLoginSettings", "container/container[1]/container[3]/tabpagelist[@automationid='SyncTabControl']/tabpage[@automationid='ProfileTabItem']/?/?/list[@automationid='ProfileRegion']//list[@automationid='UsersettingsRegion']/?/?/container[@automationid='UserSettingExpander']", parentFolder, 30000, null, false, "67c803e2-5f5f-4e0d-8d4e-8697d46a6e5c", "")
            {
                _login_buttonInfo = new RepoItemInfo(this, "login_button", ".//button[@text='Logon']", 30000, null, "2bc11cb2-5140-47bb-82b9-0bea8018bec1");
                _password_fieldInfo = new RepoItemInfo(this, "password_field", ".//text[@automationid='PwBox']", 30000, null, "9e95de50-05ea-4682-8426-ce5d88a928bc");
                _username_fieldInfo = new RepoItemInfo(this, "username_field", ".//text[@automationid='UserName']/element[2]", 30000, null, "21aa4a89-8c1c-4a30-b25e-e156d4bf433b");
                _expand_loginform_buttonInfo = new RepoItemInfo(this, "expand_loginForm_button", "?/?/checkbox[@automationid='HeaderSite']/?/?/element[@automationid='circle']", 30000, null, "29a5cadc-d6bb-434e-927d-8bc77d3cc62f");
                _logout_buttonInfo = new RepoItemInfo(this, "logout_button", ".//button[@text='Logout']", 30000, null, "e55d19fe-9b94-4ee5-b31c-83e6a40af5d5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("67c803e2-5f5f-4e0d-8d4e-8697d46a6e5c")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("67c803e2-5f5f-4e0d-8d4e-8697d46a6e5c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The login_button item.
            /// </summary>
            [RepositoryItem("2bc11cb2-5140-47bb-82b9-0bea8018bec1")]
            public virtual Ranorex.Button login_button
            {
                get
                {
                    return _login_buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The login_button item info.
            /// </summary>
            [RepositoryItemInfo("2bc11cb2-5140-47bb-82b9-0bea8018bec1")]
            public virtual RepoItemInfo login_buttonInfo
            {
                get
                {
                    return _login_buttonInfo;
                }
            }

            /// <summary>
            /// The password_field item.
            /// </summary>
            [RepositoryItem("9e95de50-05ea-4682-8426-ce5d88a928bc")]
            public virtual Ranorex.Text password_field
            {
                get
                {
                    return _password_fieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The password_field item info.
            /// </summary>
            [RepositoryItemInfo("9e95de50-05ea-4682-8426-ce5d88a928bc")]
            public virtual RepoItemInfo password_fieldInfo
            {
                get
                {
                    return _password_fieldInfo;
                }
            }

            /// <summary>
            /// The username_field item.
            /// </summary>
            [RepositoryItem("21aa4a89-8c1c-4a30-b25e-e156d4bf433b")]
            public virtual Ranorex.Unknown username_field
            {
                get
                {
                    return _username_fieldInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The username_field item info.
            /// </summary>
            [RepositoryItemInfo("21aa4a89-8c1c-4a30-b25e-e156d4bf433b")]
            public virtual RepoItemInfo username_fieldInfo
            {
                get
                {
                    return _username_fieldInfo;
                }
            }

            /// <summary>
            /// The expand_loginForm_button item.
            /// </summary>
            [RepositoryItem("29a5cadc-d6bb-434e-927d-8bc77d3cc62f")]
            public virtual Ranorex.Unknown expand_loginForm_button
            {
                get
                {
                    return _expand_loginform_buttonInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The expand_loginForm_button item info.
            /// </summary>
            [RepositoryItemInfo("29a5cadc-d6bb-434e-927d-8bc77d3cc62f")]
            public virtual RepoItemInfo expand_loginForm_buttonInfo
            {
                get
                {
                    return _expand_loginform_buttonInfo;
                }
            }

            /// <summary>
            /// The logout_button item.
            /// </summary>
            [RepositoryItem("e55d19fe-9b94-4ee5-b31c-83e6a40af5d5")]
            public virtual Ranorex.Button logout_button
            {
                get
                {
                    return _logout_buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The logout_button item info.
            /// </summary>
            [RepositoryItemInfo("e55d19fe-9b94-4ee5-b31c-83e6a40af5d5")]
            public virtual RepoItemInfo logout_buttonInfo
            {
                get
                {
                    return _logout_buttonInfo;
                }
            }
        }

        /// <summary>
        /// The Win_taskBarAppFolder folder.
        /// </summary>
        [RepositoryFolder("613e494b-6889-434f-9255-1e70dc948e7b")]
        public partial class Win_taskBarAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _win_showsystemtray_buttonInfo;
            RepoItemInfo _organise_photos_taskbar_iconInfo;

            /// <summary>
            /// Creates a new win_taskBar  folder.
            /// </summary>
            public Win_taskBarAppFolder(RepoGenBaseFolder parentFolder) :
                    base("win_taskBar", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "613e494b-6889-434f-9255-1e70dc948e7b", "")
            {
                _win_showsystemtray_buttonInfo = new RepoItemInfo(this, "win_showSystemTray_button", "?/?/button[@text='']", 30000, null, "fdbbae03-8a4c-46fb-92c7-473f1483d858");
                _organise_photos_taskbar_iconInfo = new RepoItemInfo(this, "organise_photos_taskBar_icon", "?/?/container[@caption='Running applications']/?/?/toolbar[@accessiblename='Running applications']/button[@accessiblename='Organise.Photos Sync Tool']", 30000, null, "e726cd48-fdd3-495f-bde2-4c9fb9fe03ab");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("613e494b-6889-434f-9255-1e70dc948e7b")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("613e494b-6889-434f-9255-1e70dc948e7b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The win_showSystemTray_button item.
            /// </summary>
            [RepositoryItem("fdbbae03-8a4c-46fb-92c7-473f1483d858")]
            public virtual Ranorex.Button win_showSystemTray_button
            {
                get
                {
                    return _win_showsystemtray_buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The win_showSystemTray_button item info.
            /// </summary>
            [RepositoryItemInfo("fdbbae03-8a4c-46fb-92c7-473f1483d858")]
            public virtual RepoItemInfo win_showSystemTray_buttonInfo
            {
                get
                {
                    return _win_showsystemtray_buttonInfo;
                }
            }

            /// <summary>
            /// The organise_photos_taskBar_icon item.
            /// </summary>
            [RepositoryItem("e726cd48-fdd3-495f-bde2-4c9fb9fe03ab")]
            public virtual Ranorex.Button organise_photos_taskBar_icon
            {
                get
                {
                    return _organise_photos_taskbar_iconInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The organise_photos_taskBar_icon item info.
            /// </summary>
            [RepositoryItemInfo("e726cd48-fdd3-495f-bde2-4c9fb9fe03ab")]
            public virtual RepoItemInfo organise_photos_taskBar_iconInfo
            {
                get
                {
                    return _organise_photos_taskbar_iconInfo;
                }
            }
        }

        /// <summary>
        /// The Win_systemTray_IconsAppFolder folder.
        /// </summary>
        [RepositoryFolder("d4cdfe2f-d598-4cc9-87e2-0ea2262a0836")]
        public partial class Win_systemTray_IconsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _organise_photos_systemtray_iconInfo;

            /// <summary>
            /// Creates a new win_systemTray_Icons  folder.
            /// </summary>
            public Win_systemTray_IconsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("win_systemTray_Icons", "/form[@processname='explorer']", parentFolder, 30000, null, true, "d4cdfe2f-d598-4cc9-87e2-0ea2262a0836", "")
            {
                _organise_photos_systemtray_iconInfo = new RepoItemInfo(this, "organise_photos_systemTray_icon", "?/?/button[@text~'^Double-click\\ for\\ window,\\ ']", 30000, null, "e87c03c3-b59c-4c23-93a9-21a43dd19153");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d4cdfe2f-d598-4cc9-87e2-0ea2262a0836")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d4cdfe2f-d598-4cc9-87e2-0ea2262a0836")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The organise_photos_systemTray_icon item.
            /// </summary>
            [RepositoryItem("e87c03c3-b59c-4c23-93a9-21a43dd19153")]
            public virtual Ranorex.Button organise_photos_systemTray_icon
            {
                get
                {
                    return _organise_photos_systemtray_iconInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The organise_photos_systemTray_icon item info.
            /// </summary>
            [RepositoryItemInfo("e87c03c3-b59c-4c23-93a9-21a43dd19153")]
            public virtual RepoItemInfo organise_photos_systemTray_iconInfo
            {
                get
                {
                    return _organise_photos_systemtray_iconInfo;
                }
            }
        }

        /// <summary>
        /// The Organise_photos_systemTray_optionsAppFolder folder.
        /// </summary>
        [RepositoryFolder("34c5abc1-46f6-4e61-9432-84b94ecf775e")]
        public partial class Organise_photos_systemTray_optionsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _organise_photos_systemtray_exitInfo;

            /// <summary>
            /// Creates a new organise_photos_systemTray_options  folder.
            /// </summary>
            public Organise_photos_systemTray_optionsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("organise_photos_systemTray_options", "/contextmenu[@processname='Albelli.Frontend.MHNSync' and @win32ownerwindowlevel='0']", parentFolder, 30000, null, false, "34c5abc1-46f6-4e61-9432-84b94ecf775e", "")
            {
                _organise_photos_systemtray_exitInfo = new RepoItemInfo(this, "organise_photos_systemTray_exit", "menuitem[@text='Exit']//text[@caption='Exit']", 30000, null, "31bd0780-10f0-447a-a777-1d9cb1489a89");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("34c5abc1-46f6-4e61-9432-84b94ecf775e")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("34c5abc1-46f6-4e61-9432-84b94ecf775e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The organise_photos_systemTray_exit item.
            /// </summary>
            [RepositoryItem("31bd0780-10f0-447a-a777-1d9cb1489a89")]
            public virtual Ranorex.Text organise_photos_systemTray_exit
            {
                get
                {
                    return _organise_photos_systemtray_exitInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The organise_photos_systemTray_exit item info.
            /// </summary>
            [RepositoryItemInfo("31bd0780-10f0-447a-a777-1d9cb1489a89")]
            public virtual RepoItemInfo organise_photos_systemTray_exitInfo
            {
                get
                {
                    return _organise_photos_systemtray_exitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}